# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'typewriter.ui'
#
# Created: Sun Feb  6 19:20:15 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_form_typewriter(object):
    def setupUi(self, form_typewriter):
        form_typewriter.setObjectName("form_typewriter")
        form_typewriter.resize(1068, 359)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(form_typewriter.sizePolicy().hasHeightForWidth())
        form_typewriter.setSizePolicy(sizePolicy)
        self.pushButton_A = QtGui.QPushButton(form_typewriter)
        self.pushButton_A.setGeometry(QtCore.QRect(10, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_A.setFont(font)
        self.pushButton_A.setObjectName("pushButton_A")
        self.pushButton_B = QtGui.QPushButton(form_typewriter)
        self.pushButton_B.setGeometry(QtCore.QRect(90, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_B.setFont(font)
        self.pushButton_B.setObjectName("pushButton_B")
        self.pushButton_C = QtGui.QPushButton(form_typewriter)
        self.pushButton_C.setGeometry(QtCore.QRect(170, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_C.setFont(font)
        self.pushButton_C.setObjectName("pushButton_C")
        self.pushButton_D = QtGui.QPushButton(form_typewriter)
        self.pushButton_D.setGeometry(QtCore.QRect(250, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_D.setFont(font)
        self.pushButton_D.setObjectName("pushButton_D")
        self.pushButton_E = QtGui.QPushButton(form_typewriter)
        self.pushButton_E.setGeometry(QtCore.QRect(330, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_E.setFont(font)
        self.pushButton_E.setObjectName("pushButton_E")
        self.pushButton_F = QtGui.QPushButton(form_typewriter)
        self.pushButton_F.setGeometry(QtCore.QRect(410, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_F.setFont(font)
        self.pushButton_F.setObjectName("pushButton_F")
        self.pushButton_G = QtGui.QPushButton(form_typewriter)
        self.pushButton_G.setGeometry(QtCore.QRect(490, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_G.setFont(font)
        self.pushButton_G.setObjectName("pushButton_G")
        self.pushButton_H = QtGui.QPushButton(form_typewriter)
        self.pushButton_H.setGeometry(QtCore.QRect(570, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_H.setFont(font)
        self.pushButton_H.setObjectName("pushButton_H")
        self.pushButton_I = QtGui.QPushButton(form_typewriter)
        self.pushButton_I.setGeometry(QtCore.QRect(650, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_I.setFont(font)
        self.pushButton_I.setObjectName("pushButton_I")
        self.pushButton_J = QtGui.QPushButton(form_typewriter)
        self.pushButton_J.setGeometry(QtCore.QRect(730, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_J.setFont(font)
        self.pushButton_J.setObjectName("pushButton_J")
        self.pushButton_L = QtGui.QPushButton(form_typewriter)
        self.pushButton_L.setGeometry(QtCore.QRect(90, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_L.setFont(font)
        self.pushButton_L.setObjectName("pushButton_L")
        self.pushButton_S = QtGui.QPushButton(form_typewriter)
        self.pushButton_S.setGeometry(QtCore.QRect(650, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_S.setFont(font)
        self.pushButton_S.setObjectName("pushButton_S")
        self.pushButton_M = QtGui.QPushButton(form_typewriter)
        self.pushButton_M.setGeometry(QtCore.QRect(170, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_M.setFont(font)
        self.pushButton_M.setObjectName("pushButton_M")
        self.pushButton_P = QtGui.QPushButton(form_typewriter)
        self.pushButton_P.setGeometry(QtCore.QRect(410, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_P.setFont(font)
        self.pushButton_P.setObjectName("pushButton_P")
        self.pushButton_K = QtGui.QPushButton(form_typewriter)
        self.pushButton_K.setGeometry(QtCore.QRect(10, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_K.setFont(font)
        self.pushButton_K.setObjectName("pushButton_K")
        self.pushButton_O = QtGui.QPushButton(form_typewriter)
        self.pushButton_O.setGeometry(QtCore.QRect(330, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_O.setFont(font)
        self.pushButton_O.setObjectName("pushButton_O")
        self.pushButton_Q = QtGui.QPushButton(form_typewriter)
        self.pushButton_Q.setGeometry(QtCore.QRect(490, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Q.setFont(font)
        self.pushButton_Q.setObjectName("pushButton_Q")
        self.pushButton_T = QtGui.QPushButton(form_typewriter)
        self.pushButton_T.setGeometry(QtCore.QRect(730, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_T.setFont(font)
        self.pushButton_T.setObjectName("pushButton_T")
        self.pushButton_R = QtGui.QPushButton(form_typewriter)
        self.pushButton_R.setGeometry(QtCore.QRect(570, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_R.setFont(font)
        self.pushButton_R.setObjectName("pushButton_R")
        self.pushButton_N = QtGui.QPushButton(form_typewriter)
        self.pushButton_N.setGeometry(QtCore.QRect(250, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_N.setFont(font)
        self.pushButton_N.setObjectName("pushButton_N")
        self.pushButton_V = QtGui.QPushButton(form_typewriter)
        self.pushButton_V.setGeometry(QtCore.QRect(90, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_V.setFont(font)
        self.pushButton_V.setObjectName("pushButton_V")
        self.pushButton_QuestionMark = QtGui.QPushButton(form_typewriter)
        self.pushButton_QuestionMark.setGeometry(QtCore.QRect(570, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_QuestionMark.setFont(font)
        self.pushButton_QuestionMark.setObjectName("pushButton_QuestionMark")
        self.pushButton_W = QtGui.QPushButton(form_typewriter)
        self.pushButton_W.setGeometry(QtCore.QRect(170, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_W.setFont(font)
        self.pushButton_W.setObjectName("pushButton_W")
        self.pushButton_Z = QtGui.QPushButton(form_typewriter)
        self.pushButton_Z.setGeometry(QtCore.QRect(410, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Z.setFont(font)
        self.pushButton_Z.setObjectName("pushButton_Z")
        self.pushButton_U = QtGui.QPushButton(form_typewriter)
        self.pushButton_U.setGeometry(QtCore.QRect(10, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_U.setFont(font)
        self.pushButton_U.setObjectName("pushButton_U")
        self.pushButton_Y = QtGui.QPushButton(form_typewriter)
        self.pushButton_Y.setGeometry(QtCore.QRect(330, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Y.setFont(font)
        self.pushButton_Y.setObjectName("pushButton_Y")
        self.pushButton_Comma = QtGui.QPushButton(form_typewriter)
        self.pushButton_Comma.setGeometry(QtCore.QRect(650, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Comma.setFont(font)
        self.pushButton_Comma.setObjectName("pushButton_Comma")
        self.pushButton_Exclamation = QtGui.QPushButton(form_typewriter)
        self.pushButton_Exclamation.setGeometry(QtCore.QRect(490, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Exclamation.setFont(font)
        self.pushButton_Exclamation.setObjectName("pushButton_Exclamation")
        self.pushButton_X = QtGui.QPushButton(form_typewriter)
        self.pushButton_X.setGeometry(QtCore.QRect(250, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_X.setFont(font)
        self.pushButton_X.setObjectName("pushButton_X")
        self.pushButton_Space1 = QtGui.QPushButton(form_typewriter)
        self.pushButton_Space1.setGeometry(QtCore.QRect(810, 120, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Space1.setFont(font)
        self.pushButton_Space1.setObjectName("pushButton_Space1")
        self.pushButton_Space2 = QtGui.QPushButton(form_typewriter)
        self.pushButton_Space2.setGeometry(QtCore.QRect(810, 200, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Space2.setFont(font)
        self.pushButton_Space2.setObjectName("pushButton_Space2")
        self.pushButton_Space3 = QtGui.QPushButton(form_typewriter)
        self.pushButton_Space3.setGeometry(QtCore.QRect(810, 280, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Space3.setFont(font)
        self.pushButton_Space3.setObjectName("pushButton_Space3")
        self.plainTextEdit = QtGui.QPlainTextEdit(form_typewriter)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 16, 1041, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_Period1 = QtGui.QPushButton(form_typewriter)
        self.pushButton_Period1.setGeometry(QtCore.QRect(910, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Period1.setFont(font)
        self.pushButton_Period1.setObjectName("pushButton_Period1")
        self.pushButton_Period2 = QtGui.QPushButton(form_typewriter)
        self.pushButton_Period2.setGeometry(QtCore.QRect(910, 200, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Period2.setFont(font)
        self.pushButton_Period2.setObjectName("pushButton_Period2")
        self.pushButton_Period3 = QtGui.QPushButton(form_typewriter)
        self.pushButton_Period3.setGeometry(QtCore.QRect(910, 280, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Period3.setFont(font)
        self.pushButton_Period3.setObjectName("pushButton_Period3")
        self.pushButton_Enter = QtGui.QPushButton(form_typewriter)
        self.pushButton_Enter.setGeometry(QtCore.QRect(730, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Enter.setFont(font)
        self.pushButton_Enter.setObjectName("pushButton_Enter")
        self.pushButton_Backspace2 = QtGui.QPushButton(form_typewriter)
        self.pushButton_Backspace2.setGeometry(QtCore.QRect(980, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Backspace2.setFont(font)
        self.pushButton_Backspace2.setObjectName("pushButton_Backspace2")
        self.pushButton_Clear = QtGui.QPushButton(form_typewriter)
        self.pushButton_Clear.setGeometry(QtCore.QRect(980, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Clear.setFont(font)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.pushButton_Backspace1 = QtGui.QPushButton(form_typewriter)
        self.pushButton_Backspace1.setGeometry(QtCore.QRect(980, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Backspace1.setFont(font)
        self.pushButton_Backspace1.setObjectName("pushButton_Backspace1")

        self.retranslateUi(form_typewriter)
        QtCore.QObject.connect(self.pushButton_Clear, QtCore.SIGNAL("clicked()"), self.plainTextEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(form_typewriter)
        form_typewriter.setTabOrder(self.pushButton_A, self.pushButton_B)
        form_typewriter.setTabOrder(self.pushButton_B, self.pushButton_C)
        form_typewriter.setTabOrder(self.pushButton_C, self.pushButton_D)
        form_typewriter.setTabOrder(self.pushButton_D, self.pushButton_E)
        form_typewriter.setTabOrder(self.pushButton_E, self.pushButton_F)
        form_typewriter.setTabOrder(self.pushButton_F, self.pushButton_G)
        form_typewriter.setTabOrder(self.pushButton_G, self.pushButton_H)
        form_typewriter.setTabOrder(self.pushButton_H, self.pushButton_I)
        form_typewriter.setTabOrder(self.pushButton_I, self.pushButton_J)
        form_typewriter.setTabOrder(self.pushButton_J, self.pushButton_Space1)
        form_typewriter.setTabOrder(self.pushButton_Space1, self.pushButton_Period1)
        form_typewriter.setTabOrder(self.pushButton_Period1, self.pushButton_Backspace1)
        form_typewriter.setTabOrder(self.pushButton_Backspace1, self.pushButton_K)
        form_typewriter.setTabOrder(self.pushButton_K, self.pushButton_L)
        form_typewriter.setTabOrder(self.pushButton_L, self.pushButton_M)
        form_typewriter.setTabOrder(self.pushButton_M, self.pushButton_N)
        form_typewriter.setTabOrder(self.pushButton_N, self.pushButton_O)
        form_typewriter.setTabOrder(self.pushButton_O, self.pushButton_P)
        form_typewriter.setTabOrder(self.pushButton_P, self.pushButton_Q)
        form_typewriter.setTabOrder(self.pushButton_Q, self.pushButton_R)
        form_typewriter.setTabOrder(self.pushButton_R, self.pushButton_S)
        form_typewriter.setTabOrder(self.pushButton_S, self.pushButton_T)
        form_typewriter.setTabOrder(self.pushButton_T, self.pushButton_Space2)
        form_typewriter.setTabOrder(self.pushButton_Space2, self.pushButton_Period2)
        form_typewriter.setTabOrder(self.pushButton_Period2, self.pushButton_Backspace2)
        form_typewriter.setTabOrder(self.pushButton_Backspace2, self.pushButton_U)
        form_typewriter.setTabOrder(self.pushButton_U, self.pushButton_V)
        form_typewriter.setTabOrder(self.pushButton_V, self.pushButton_W)
        form_typewriter.setTabOrder(self.pushButton_W, self.pushButton_X)
        form_typewriter.setTabOrder(self.pushButton_X, self.pushButton_Y)
        form_typewriter.setTabOrder(self.pushButton_Y, self.pushButton_Z)
        form_typewriter.setTabOrder(self.pushButton_Z, self.pushButton_Exclamation)
        form_typewriter.setTabOrder(self.pushButton_Exclamation, self.pushButton_QuestionMark)
        form_typewriter.setTabOrder(self.pushButton_QuestionMark, self.pushButton_Comma)
        form_typewriter.setTabOrder(self.pushButton_Comma, self.pushButton_Enter)
        form_typewriter.setTabOrder(self.pushButton_Enter, self.pushButton_Space3)
        form_typewriter.setTabOrder(self.pushButton_Space3, self.pushButton_Period3)
        form_typewriter.setTabOrder(self.pushButton_Period3, self.pushButton_Clear)
        form_typewriter.setTabOrder(self.pushButton_Clear, self.plainTextEdit)

    def retranslateUi(self, form_typewriter):
        form_typewriter.setWindowTitle(QtGui.QApplication.translate("form_typewriter", "KinectACI - Typewriter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_A.setText(QtGui.QApplication.translate("form_typewriter", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_B.setText(QtGui.QApplication.translate("form_typewriter", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_C.setText(QtGui.QApplication.translate("form_typewriter", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_D.setText(QtGui.QApplication.translate("form_typewriter", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_E.setText(QtGui.QApplication.translate("form_typewriter", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_F.setText(QtGui.QApplication.translate("form_typewriter", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_G.setText(QtGui.QApplication.translate("form_typewriter", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_H.setText(QtGui.QApplication.translate("form_typewriter", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_I.setText(QtGui.QApplication.translate("form_typewriter", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_J.setText(QtGui.QApplication.translate("form_typewriter", "J", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_L.setText(QtGui.QApplication.translate("form_typewriter", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_S.setText(QtGui.QApplication.translate("form_typewriter", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_M.setText(QtGui.QApplication.translate("form_typewriter", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_P.setText(QtGui.QApplication.translate("form_typewriter", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_K.setText(QtGui.QApplication.translate("form_typewriter", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_O.setText(QtGui.QApplication.translate("form_typewriter", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Q.setText(QtGui.QApplication.translate("form_typewriter", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_T.setText(QtGui.QApplication.translate("form_typewriter", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_R.setText(QtGui.QApplication.translate("form_typewriter", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_N.setText(QtGui.QApplication.translate("form_typewriter", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_V.setText(QtGui.QApplication.translate("form_typewriter", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_QuestionMark.setText(QtGui.QApplication.translate("form_typewriter", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_W.setText(QtGui.QApplication.translate("form_typewriter", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Z.setText(QtGui.QApplication.translate("form_typewriter", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_U.setText(QtGui.QApplication.translate("form_typewriter", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Y.setText(QtGui.QApplication.translate("form_typewriter", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Comma.setText(QtGui.QApplication.translate("form_typewriter", ",", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Exclamation.setText(QtGui.QApplication.translate("form_typewriter", "!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_X.setText(QtGui.QApplication.translate("form_typewriter", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Space1.setText(QtGui.QApplication.translate("form_typewriter", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Space2.setText(QtGui.QApplication.translate("form_typewriter", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Space3.setText(QtGui.QApplication.translate("form_typewriter", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Period1.setText(QtGui.QApplication.translate("form_typewriter", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Period2.setText(QtGui.QApplication.translate("form_typewriter", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Period3.setText(QtGui.QApplication.translate("form_typewriter", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Enter.setText(QtGui.QApplication.translate("form_typewriter", "Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Backspace2.setText(QtGui.QApplication.translate("form_typewriter", "BkSpc", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Clear.setText(QtGui.QApplication.translate("form_typewriter", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Backspace1.setText(QtGui.QApplication.translate("form_typewriter", "BkSpc", None, QtGui.QApplication.UnicodeUTF8))

